### PR TITLE
Version 2.0 -- Fixes + Docker file multiple options support

### PR DESCRIPTION
**Pull request by laalex**
- Added a base function to process the 1 level docker config options, array config options and object config options
- Fixed bug that prevented the docker-compose to parse the file in the object and array values (there was one space needed between the `-` and the `value` of the element
- Refactored some things
- Wrote a few new tests to check the new implementation for all the docker-compose.yml config params

- Added myself to contributors
- Changed version to 2.0

### CODE REVIEW

**Comment by laalex** [comment]
@tudvari I forgot to update the changelog in this PR. Also I think that after this version we can recursively implement for all levels of the docker-compose.yml file.

**Comment by tudvari** [comment]
@laalex : I would like to ask a little time, can I check your PR tomorrow, because I am not able to work on this weekend.

**Comment by laalex** [comment]
Hey, sure thing mate. Don't rush. It's Easter over here this weekend so
I'll be back on monday :)

On Saturday, 30 April 2016, Tibor Udvari <notifications@github.com> wrote:

> @laalex <https://github.com/laalex> : I would like to ask a little time,
> can I check your PR tomorrow, because I am not able to work on this weekend.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tudvari/docker-composer/pull/1#issuecomment-215933423>
>


-- 


---------------------------------------------------------------------------------------
Lamba A. Alexandru
+40 725 671 161

Follow me on Twitter @AlexandruLamba <http://twitter.com/alexandrulamba>
http://www.linkedin.com/in/alexandrulamba

**Comment by tudvari** [comment]
Thanks for the PR, I merged it into the master. NPM publish is also on the way.

**Comment by laalex** [comment]
Thanks a lot mate

On Tuesday, 3 May 2016, Tibor Udvari <notifications@github.com> wrote:

> Merged #1 <https://github.com/tudvari/docker-composer/pull/1>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tudvari/docker-composer/pull/1#event-649317306>
>


-- 


---------------------------------------------------------------------------------------
Lamba A. Alexandru
+40 725 671 161

Follow me on Twitter @AlexandruLamba <http://twitter.com/alexandrulamba>
http://www.linkedin.com/in/alexandrulamba

**Pull request merged**
